server {
    listen 80;
    server_name localhost;

    # Корневая директория, откуда Nginx будет отдавать файлы
    root /usr/share/nginx/html;
    # Файл по умолчанию
    index mobile.html;

    # Для корректной работы SPA (Single Page Application)
    # Все запросы, которые не находят файл, перенаправляются на mobile.html
    location / {
        try_files $uri $uri/ /mobile.html;
    }
}